### ISSUE TITLE
Calendly integration is not working

### ISSUE THREAD

**Issue by macedogm** [pondersource/connectyourbooks.com#1]
Just to let you know that Calendly integration is not working in the site. The error message is `This Calendly URL is not valid`.

![image](https://user-images.githubusercontent.com/17654553/115466215-1044b400-a230-11eb-848c-5d9aaa9f2a38.png)

**Comment by michielbdejong** [comment]
Ah, thanks for noticing!

**Comment by konnodonnoi** [comment]
is there a known fix for this? i'm experiencing this exact same issue at the moment
